//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.27 at 09:59:06 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xpadro.spring.samples.com/orders")
package xpadro.spring.integration.types;
